version: '3.7'
services:
  app:
    build: ./docker/php-apache
    container_name: container-app
    working_dir: /var/www/html
    volumes:
      - ./api/:/var/www/html
      - ./docker/php-apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: mariadb:11.1
    container_name: database-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: dPdOGs46sj
      MARIADB_DATABASE : comidatela
      MARIADB_USER : comidatela
      MARIADB_PASSWORD: acWa545Ksdf4
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql